# Cours 1 : Rappels Python + Analyse et retraitement de la donné

## 1. Préambule

L'objectif de cette séance (3h) est de construire une base de données propre pour la modélisation, tout en analysant les caractéristiques du portefeuille.

# Rappels Python

### Numériques, calculs élémentaires et imports

In [1]:
print(3+4)
print(5*2.5)
print(type(3))
print(type(2.5))
a=2**90
print(a)
print(type(a))

7
12.5
<class 'int'>
<class 'float'>
1237940039285380274899124224
<class 'int'>

In [3]:
import math
import pandas as pd

#from math import *
#help(math)
print (math.sqrt(3))
print (math.floor(3.2))
print (math.cos(math.pi/3.0))

1.7320508075688772
3
0.5000000000000001

### Chaine de caractères

In [4]:
print('33' + "42")
a="toto est toto"
a[4:]
#Tout est objet
print(a.split(' '))

3342
['toto', 'est', 'toto']

In [5]:
salutation = "Bonjour, monsieur {0}. Comment allez vous en ce {1}?".format("XX", "Mardi 19 septembre")
print(salutation)

Bonjour, monsieur XX. Comment allez vous en ce Mardi 19 septembre?

In [6]:
len("toto")

4

### Les listes

In [7]:
a = [1,'q',2,3,5,8,'TOTO']
print (a[1])
print (a[-1])
print (a[1:3])
print (a[-4:-2])
print([5]*4)

q
TOTO
['q', 2]
[3, 5]
[5, 5, 5, 5]

In [8]:
print (range(4, 10))
print (range(5, 50, 3))
print ([3,1,4] + [1,5,9])
print (len(range(4, 10)))

range(4, 10)
range(5, 50, 3)
[3, 1, 4, 1, 5, 9]
6

### Les tests

In [9]:
a = 2
if 5 > a:
    print ("Cinq!")
else:
    print ("a!")

#Zoom sur indentation
num=3
if num == 1:
    print ("C'est 1")
elif num == 2:
    print ("C'est 2")
elif num == 3:
    print ("C'est 3")
else :
    print ("Autre que 1, 2 et 3")

print(num in [1,2,3])
print(num not in [1,2,3])
print(num != 5)

print(num in [1,2,3] and num >0)

print(not 5==3)

Cinq!
C'est 3
True
False
True
True
True

### Les boucles

In [10]:
a=[3,4,5]
#Boucle for
for i in range(len(a)):
    a[i] += 3
print (a)
%timeit for i in range(len(a)):a[i] += 3
print (a)

b=[3,4,5]
print([i+3 for i in b])
%timeit [i+3 for i in b]
print (b)

for i,item in enumerate(b):
    print(i,item)

[6, 7, 8]
186 ns ± 0.414 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
[243333339, 243333340, 243333341]
[6, 7, 8]
101 ns ± 0.23 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
[3, 4, 5]
0 3
1 4
2 5

In [11]:
#Boucle While , break et continue
print("démarrage boucle")
i=0
while i<100:
    print(i)
    i+=1
    if i==52:
        i+=10
        print("increment de 10")
        continue
    i+=2
    if i ==77:
        break

démarrage boucle
0
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
increment de 10
62
65
68
71
74

### Les fonctions

In [12]:
def square(x):
    return x*x
print (square(3))

9

### Pandas - Gestion de DataFrame

Les principales possibilités de cette librairie sont :

- __récupérer des données__ depuis des fichiers CSV, tableaux Excel, des pages web, etc. ;
- grouper, découper, alléger, déplacer, écrire les données sous forme de __DataFrame__, tracer des graphiques simplifiés ;
- ces données peuvent être à une ou deux dimensions, ou encore temporelles avec ou sans périodicité.

Le développement de cette bibliothèque s'inscrit dans la problématique de disposer d'outils pour **manipuler de gros volumes de données dans le but de leur exploitation scientifique ou commerciale**.

####  Series

Le type de base dans Pandas est la série. Une série est un vecteur de valeurs de variables.

1. Importer **la librairie pandas** et créer **une série contenant la suite des chiffres de 1 à 5 et des index alphabétiques de "a" à "e"**. 
2. **Afficher cette série.**
3. **Afficher ses index.**
4. **Afficher sa moyenne.**
5. **Afficher la valeur de l'index "b" de cette série**

In [13]:
import pandas as pd 

sr = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

print("series:","\n", sr)

print(sr.index)

print("mean:", sr.mean())

print("value at 'b':", sr['b'])

series:
 a    1
b    2
c    3
d    4
e    5
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
mean: 3.0
value at 'b': 2

#### Dataframes

Le dataframe est l’**extension en 2 dimensions des series**. Il peut être vu comme un empilement de series dont les index sont partagés (et donc intrinsèquement alignés), ou comme dans un tableur où les index sont les numéros de lignes et les noms des series les noms des colonnes.

Un dataframe se comporte comme un dictionnaire dont les cléss sont les noms des colonnes et les valeurs sont des series.
On peut créer un dataframe à partir de dictionnaires, de liste de listes ou de liste de series, d’arrays numpy, de fichier Excel ou CSV, depuis des bases de données, …

6. Créer **deux séries s et t** contenant **un échantillon de 4 valeurs issues d'une loi normale centrée réduite** et ayant pour **index** :
    - **1, 2, 3, 5 pour s**
    - **1, 2, 3, 4 pour t**

Afficher ces séries.

In [14]:
from numpy.random import standard_normal

In [15]:
s = pd.Series([1,2,3,5])
t = pd.Series([1,2,3,4])

print("s:", s)
print("t:", t)

s: 0    1
1    2
2    3
3    5
dtype: int64
t: 0    1
1    2
2    3
3    4
dtype: int64

7. Créer **une dataframe** contenant **les deux séries, avec leur nom pour noms de colonnes.** L'afficher.

In [16]:
df = pd.DataFrame({'s' : s, 't' : t})

print("DataFrame:\n", df)

DataFrame:
    s  t
0  1  1
1  2  2
2  3  3
3  5  4

8. **Les opérations sur une DataFrame :**

Créer **une nouvelle colonne "SUM**", ayant pour valeur **la somme des deux séries ligne à ligne**. Afficher la DataFrame.

In [17]:
df['SUM'] = df['s'] + df['t']
print("DataFrame with sum:\n", df)

DataFrame with sum:
    s  t  SUM
0  1  1    2
1  2  2    4
2  3  3    6
3  5  4    9

9. Afficher la moyenne de la colonne "SUM".

In [18]:
print("mean of 'SUM':", df['SUM'].mean())

mean of 'SUM': 5.25

### La bibliothèque NumPy

**La bibliothèque NumPy permet d’effectuer des calculs numériques avec Python. Elle introduit une gestion facilitée des tableaux de nombres.**

Pour info : Pandas ou Numpy ? Dans le cas de Pandas, ce ne sont pas tout-à-fait des matrices mais des tables de données : la même table peut contenir différents types de données, des nombres, des chaînes de caractères, des booléens, des dates… Les données se manipulent comme des bases de données et les Dataframe de pandas sont optimisées pour ça. Chaque colonne porte un nom. Numpy propose des matrices à une ou plusieurs dimensions optimisées pour le calcul matriciel. Ces matrices ne contiennent que des nombres et tous du même type.

**--> Pour faire des calculs matriciels, on choisit numpy. Pour faire de la gestion de base de données telle qu'une jointure de table, on choisit pandas.**

10. A l'aide de la librairie Numpy, générer **un échantillon issu d'une loi normale centrée réduite de 250 valeurs**. L'**afficher**.
11. Créer **une série contenant l'échantillon précédent**. Les **index** de cette série consisteront en **un historique journalier à compter du 01/01/2012** (*indice : pour la définition des index, utiliser la fonction date_range de pandas*). **Afficher cette série**.
12. Importer la **fonction offsets de pandas** et créer **une nouvelle range d'index** en repartant de la range d'index précédente mais en sélectionnant **un jour sur deux**. **Afficher cette range d'index**.

In [19]:
import numpy as np

norm = np.random.normal(loc=0.0, scale=1.0, size=250)

In [20]:
dates = pd.date_range('20120101', periods=250)
sr_norm = pd.Series(norm, index = dates)

print("Normal distribution seri#Ecrivez votre code icies:\n", sr_norm)

Normal distribution series:
 2012-01-01    0.989203
2012-01-02    0.390953
2012-01-03   -0.095145
2012-01-04   -1.861817
2012-01-05   -0.024847
                ...
2012-09-02   -0.612353
2012-09-03   -0.221533
2012-09-04    1.303021
2012-09-05    1.685707
2012-09-06    0.508734
Freq: D, Length: 250, dtype: float64

In [21]:
from pandas import offsets

dates_1_on_2 = pd.date_range('20120101', periods=250, freq=offsets.Day(2))
sr_norm_1_on_2 = pd.Series(norm, index = dates_1_on_2)
print("Normal distribution series with 1 on 2 days:\n", sr_norm_1_on_2)

Normal distribution series with 1 on 2 days:
 2012-01-01    0.989203
2012-01-03    0.390953
2012-01-05   -0.095145
2012-01-07   -1.861817
2012-01-09   -0.024847
                ...
2013-05-05   -0.612353
2013-05-07   -0.221533
2013-05-09    1.303021
2013-05-11    1.685707
2013-05-13    0.508734
Freq: 2D, Length: 250, dtype: float64

# Travail pratique

## 3. Préparation du workspace

### Import de librairies

In [23]:
#Data frame
import pandas as pd

#Graphiques
import seaborn as sns
sns.set()
import plotly.express as px
import plotly.graph_objects as gp

### Constantes

In [24]:
input_path = "./1_inputs"
output_path = "./2_outputs"

## 4. Import et visualisation des données

### Import des données

In [27]:
path = input_path + '/base_modelisation_2025.csv'
data_set = pd.read_csv(path,sep=";",decimal=",")

### Une première observation des données

In [28]:
# Premières lignes
data_set.head()

,ANNEE_CTR,CONTRAT_ANCIENNETE,FREQUENCE_PAIEMENT_COTISATION,GROUPE_KM,ZONE_RISQUE,AGE_ASSURE_PRINCIPAL,GENRE,DEUXIEME_CONDUCTEUR,ANCIENNETE_PERMIS,ANNEE_CONSTRUCTION,ENERGIE,EQUIPEMENT_SECURITE,PUISSANCE_VEHICULE,VALEUR_DU_BIEN,NB,CHARGE,EXPO
0,2023,"(-1,0]",ANNUEL,[20000;40000[,B,54,M,False,47,2020.0,ESSENCE,FAUX,NaN,[10000;15000[,0,0.0,0.672131
1,2023,"(-1,0]",ANNUEL,[20000;40000[,B,88,F,True,55,2022.0,DIESEL,VRAI,"(85,96]",[20000;25000[,0,0.0,0.631148
2,2025,"(1,2]",ANNUEL,[0;20000[,D,35,F,True,16,2021.0,ESSENCE,FAUX,"(74,80]",[15000;20000[,0,0.0,0.821918
3,2025,"(2,5]",ANNUEL,[0;20000[,C,46,NaN,False,44,2022.0,ESSENCE,VRAI,"(120,596]",[35000;99999[,0,0.0,0.832877
4,2022,"(2,5]",MENSUEL,[20000;40000[,A,46,F,False,31,2013.0,DIESEL,FAUX,"(66,74]",[10000;15000[,0,0.0,1.000000

In [29]:
# Dernières lignes
data_set.tail()

,ANNEE_CTR,CONTRAT_ANCIENNETE,FREQUENCE_PAIEMENT_COTISATION,GROUPE_KM,ZONE_RISQUE,AGE_ASSURE_PRINCIPAL,GENRE,DEUXIEME_CONDUCTEUR,ANCIENNETE_PERMIS,ANNEE_CONSTRUCTION,ENERGIE,EQUIPEMENT_SECURITE,PUISSANCE_VEHICULE,VALEUR_DU_BIEN,NB,CHARGE,EXPO
14259,2025,"(2,5]",MENSUEL,[0;20000[,D,55,M,False,49,2021.0,ESSENCE,FAUX,"(80,85]",[20000;25000[,0,0.0,0.495890
14260,2023,"(2,5]",MENSUEL,[20000;40000[,A,33,NaN,False,14,2021.0,ESSENCE,FAUX,"(1,51]",[10000;15000[,0,0.0,0.999094
14261,2021,"(-1,0]",ANNUEL,[0;20000[,A,62,NaN,False,58,2021.0,ESSENCE,VRAI,NaN,[10000;15000[,0,0.0,0.498630
14262,2022,"(-1,0]",TRIMESTRIEL,[20000;40000[,D,20,NaN,False,7,2020.0,DIESEL,FAUX,"(105,120]",[25000;35000[,0,0.0,0.024658
14263,2021,"(-1,0]",ANNUEL,[0;20000[,C,73,F,False,41,2021.0,ESSENCE,FAUX,"(1,51]",[10000;15000[,0,0.0,0.142466

In [30]:
# Synthèse des variables 
data_set.describe(include="all")

,ANNEE_CTR,CONTRAT_ANCIENNETE,FREQUENCE_PAIEMENT_COTISATION,GROUPE_KM,ZONE_RISQUE,AGE_ASSURE_PRINCIPAL,GENRE,DEUXIEME_CONDUCTEUR,ANCIENNETE_PERMIS,ANNEE_CONSTRUCTION,ENERGIE,EQUIPEMENT_SECURITE,PUISSANCE_VEHICULE,VALEUR_DU_BIEN,NB,CHARGE,EXPO
count,14264.000000,14264,14264,14261,14263,14264.000000,13522,13617,14264.000000,14058.000000,14264,14264,12089,14058,14264.000000,14264.000000,14264.000000
unique,NaN,5,3,4,17,NaN,2,2,NaN,NaN,3,2,10,6,NaN,NaN,NaN
top,NaN,"(0,1]",MENSUEL,[0;20000[,C,NaN,M,False,NaN,NaN,ESSENCE,FAUX,"(80,85]",[10000;15000[,NaN,NaN,NaN
freq,NaN,4183,6867,7665,4876,NaN,7659,10601,NaN,NaN,7312,9407,1960,3433,NaN,NaN,NaN
mean,2022.768087,NaN,NaN,NaN,NaN,44.965648,NaN,NaN,36.297602,2019.382202,NaN,NaN,NaN,NaN,0.060993,368.819292,0.757784
std,1.656104,NaN,NaN,NaN,NaN,13.685578,NaN,NaN,18.913731,3.532906,NaN,NaN,NaN,NaN,0.251886,2033.092340,0.297270
min,2020.000000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN,0.000000,1965.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.002732
25%,2021.000000,NaN,NaN,NaN,NaN,35.000000,NaN,NaN,19.000000,2018.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.561644
50%,2023.000000,NaN,NaN,NaN,NaN,44.000000,NaN,NaN,35.000000,2020.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.841096
75%,2024.000000,NaN,NaN,NaN,NaN,54.000000,NaN,NaN,53.000000,2021.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
max,2025.000000,NaN,NaN,NaN,NaN,94.000000,NaN,NaN,70.000000,2025.000000,NaN,NaN,NaN,NaN,3.000000,83421.850000,1.000000

In [31]:
#Dimensions 
data_set.shape

(14264, 17)

In [32]:
# Liste des colonnes
data_set.columns

Index(['ANNEE_CTR', 'CONTRAT_ANCIENNETE', 'FREQUENCE_PAIEMENT_COTISATION',
       'GROUPE_KM', 'ZONE_RISQUE', 'AGE_ASSURE_PRINCIPAL', 'GENRE',
       'DEUXIEME_CONDUCTEUR', 'ANCIENNETE_PERMIS', 'ANNEE_CONSTRUCTION',
       'ENERGIE', 'EQUIPEMENT_SECURITE', 'PUISSANCE_VEHICULE',
       'VALEUR_DU_BIEN', 'NB', 'CHARGE', 'EXPO'],
      dtype='str')

In [33]:
#Liste des colonnes selon leur type
data_set.dtypes

ANNEE_CTR                          int64
CONTRAT_ANCIENNETE                   str
FREQUENCE_PAIEMENT_COTISATION        str
GROUPE_KM                            str
ZONE_RISQUE                          str
AGE_ASSURE_PRINCIPAL               int64
GENRE                                str
DEUXIEME_CONDUCTEUR               object
ANCIENNETE_PERMIS                  int64
ANNEE_CONSTRUCTION               float64
ENERGIE                              str
EQUIPEMENT_SECURITE                  str
PUISSANCE_VEHICULE                   str
VALEUR_DU_BIEN                       str
NB                                 int64
CHARGE                           float64
EXPO                             float64
dtype: object

**Exercice :**
Ecrire un propgramme qui sépare les variables selon leur type (variables quantitatives, catégorielles et binaires). Pensez à identifier les variables avec des valeurs manquantes

In [52]:
for col in data_set.columns:
    if data_set[col].dtype == 'object':
        df_obj[col] = pd.DataFrame(data_set[col])
    elif data_set[col].dtype == 'int64':
        df_int[col] = pd.DataFrame(data_set[col])
    elif data_set[col].dtype == 'float64':
        df_float[col] = pd.DataFrame(data_set[col])
    elif data_set[col].dtype == 'str':
        df_str[col] = pd.DataFrame(data_set[col])

In [57]:
print("DataFrame with object type columns:\n", df_obj.head())

DataFrame with object type columns:
   DEUXIEME_CONDUCTEUR
0               False
1                True
2                True
3               False
4               False

In [58]:
print("DataFrame with int64 type columns:\n", df_int.head())

DataFrame with int64 type columns:
    NB  ANNEE_CTR  AGE_ASSURE_PRINCIPAL  ANCIENNETE_PERMIS
0   0       2023                    54                 47
1   0       2023                    88                 55
2   0       2025                    35                 16
3   0       2025                    46                 44
4   0       2022                    46                 31

In [59]:
print("DataFrame with float64 type columns:\n", df_float.head())

DataFrame with float64 type columns:
        EXPO  ANNEE_CONSTRUCTION  CHARGE
0  0.672131              2020.0     0.0
1  0.631148              2022.0     0.0
2  0.821918              2021.0     0.0
3  0.832877              2022.0     0.0
4  1.000000              2013.0     0.0

In [60]:
print("DataFrame with str type columns:\n", df_str.head())

DataFrame with str type columns:
   VALEUR_DU_BIEN CONTRAT_ANCIENNETE FREQUENCE_PAIEMENT_COTISATION  \
0  [10000;15000[             (-1,0]                        ANNUEL
1  [20000;25000[             (-1,0]                        ANNUEL
2  [15000;20000[              (1,2]                        ANNUEL
3  [35000;99999[              (2,5]                        ANNUEL
4  [10000;15000[              (2,5]                       MENSUEL

       GROUPE_KM ZONE_RISQUE GENRE  ENERGIE EQUIPEMENT_SECURITE  \
0  [20000;40000[           B     M  ESSENCE                FAUX
1  [20000;40000[           B     F   DIESEL                VRAI
2      [0;20000[           D     F  ESSENCE                FAUX
3      [0;20000[           C   NaN  ESSENCE                VRAI
4  [20000;40000[           A     F   DIESEL                FAUX

  PUISSANCE_VEHICULE
0                NaN
1            (85,96]
2            (74,80]
3          (120,596]
4            (66,74]

**Quels sont vos premiers commentaires ? Type de produit ? Périmètre temporel ? Modalités particulières ?**

### Anlayse des caractéristiques du portefeuille

**Visualiser le nombre de contrats par année**

In [110]:
print("number of contracts by year : \n", data_set.groupby('ANNEE_CTR').size())

px.histogram(data_set.sort_values('ANNEE_CTR'), x='ANNEE_CTR').update_xaxes(type='category')

number of contracts by year :
 ANNEE_CTR
2020    1778
2021    1960
2022    2323
2023    2660
2024    2817
2025    2726
dtype: int64

**Réaliser les graphiques pour autres variables présentes dans la base**

In [132]:
px.histogram(data_set.sort_values('NB'), x='NB', title='Number of sinister').update_xaxes(type='category')

In [130]:
px.histogram(data_set, x="CONTRAT_ANCIENNETE", 
            category_orders={"CONTRAT_ANCIENNETE": ["(-1,0]", "(0,1]", "(1,2]", "(2,5]", "(5,10]"]})

In [137]:
px.histogram(data_set, x='ENERGIE', title='Type of energy used')

In [136]:
px.histogram(data_set, x='GENRE', title='Gender distribution')

In [115]:
px.histogram(data_set.sort_values('AGE_ASSURE_PRINCIPAL'), x='AGE_ASSURE_PRINCIPAL', title='Age distribution').update_xaxes(type='category')

In [141]:
px.histogram(data_set, x='PUISSANCE_VEHICULE',
             category_orders={"PUISSANCE_VEHICULE": ["(1,51]", "(51,59]", "(59,66]", "(66,74]", "(74,80]", "(80,85]", "(85,96]", "(96,105]", "(105,120]", "(120,596]"]})

In [142]:
px.histogram(data_set.sort_values('ZONE_RISQUE'), x='ZONE_RISQUE')

Un graphique qui décrit de manière plus détaillée la population est la pyramide des âge  
**Tracez le graphique des pyramides des âges du portefeuille. Quels sont vos commentaires ?**

In [101]:
px.violin(data_set,y='AGE_ASSURE_PRINCIPAL',title='Age distribution')

**Exercice :** Tracez un graphique permettant de visualiser la distribution des coûts des sinistres

In [144]:
cout_sinistre = data_set[['NB', 'EXPO']].dropna()

px.line(cout_sinistre, x='EXPO', y='NB', title='Cost of sinister by exposure')

**Quels sont vos commentaires ? En particulier sur la sinistralité ?**

## 5. Retraitements

Une fois la phase d'appropriation du portefeuille passée, il est possible de nettoyer/retraiter la base de données dans le but d'obtenir une base exploitable à la modélisation

### Retraitement des NA

**Quelles possibilités s'offrent à nous ?**

**Implémentez les 3 solutions discutées**

In [45]:
data_retraitee = data_set

# Option 1 : pour la variable "PUISSANCE_VEHICULE"
data_retraitee = #Ecrivez votre code ici
data_retraitee.head()

SyntaxError: invalid syntax (3836203911.py, line 4)

In [ ]:
#Option 2 : pour les variables (GROUPE_KM,GENRE,
# ANNEE_CONSTRUCTION,VALEUR_DU_BIEN,DEUXIEME_CONDUCTEUR)

data_retraitee["GROUPE_KM"] = #Ecrivez votre code ici
data_retraitee["GENRE"] = #Ecrivez votre code ici
data_retraitee["ANNEE_CONSTRUCTION"] = #Ecrivez votre code ici
data_retraitee["VALEUR_DU_BIEN"] = #Ecrivez votre code ici
data_retraitee["DEUXIEME_CONDUCTEUR"] = #Ecrivez votre code ici

In [ ]:
#Option 3 : pour les variables (ZONE_RISQUE,DEUXIEME_CONDUCTEUR)

#Ecrivez votre code ici

In [ ]:
data_retraitee["ZONE_RISQUE"] = #Ecrivez votre code ici

### Retraitement des valeurs aberrantes

Le traitement de valeurs aberrantes est similaire au traitement des NA. Si le jeu de données contient assez d'individus, il est préférable d'écarter les individus avec des valeurs aberrantes et qui pourraient biaiser l'étude.

**Avez-vous trouvé des valeurs aberrantes ?**  
**Exercice :** Retraitez les valeurs qui vous semblent aberrantes

In [ ]:
#Ecrivez votre code ici

### Transformation de l'exposition en exposition journalière

In [ ]:
data_retraitee["EXPO"] = data_retraitee["EXPO"].multiply(365)

### Sauvegarde des données

In [ ]:
data_retraitee.to_csv("./2_outputs/base_retraitee.csv", index =  False)

## 6. Analyse de la sinistralité

Notre objectif final est de construire un modèle tarifaire. Il convient donc de construire 2 variables qui caractérisent la sinistralité :
* La fréquence de sinistres (NB / EXPO) 
* Le coût moyen (CHARGE / NB)

**Calculez la Fréquence et le coût moyen pour chaque ligne**

In [ ]:
#Ecrivez votre code ici

Les modèles tarifaires essayent d'établir un lien entre les variables explicatives et la sinistralité. C'est le travail d'un actuaire comprendre et avoir un regard critique sur les relations trouvées.  
Pour aider l'actuaire dans ce travail, la visualisation des données (FREQ, CM) en fonction des variables explicatives peut être utile.  
  
Dans ce qui suit, nous allons faire cet exercice que sur certaines variables explicatives. Cet exercice peut bien sûr être étendu aux autres variables explicatives.  
**Remarque :** 
*Attention au sens de l'analyse que vous menez. Si on s'intéresse par exemple au coût moyen de la garantie RC, ce dernier n'a pas de dépendance géographique (toute chose égale par ailleurs une victime sera indemnisée à la même hauteur à Lille ou à Marseille).*

 ### Fréquence en fonction de l'âge du conducteur

In [ ]:
#Ecrivez votre code ici

### Fréquence en fonction du genre

In [ ]:
#Ecrivez votre code ici

### Fréquence en fonction de la zone de risque

In [ ]:
#Ecrivez votre code ici

### Fréquence en fonction du carburant

In [ ]:
#Ecrivez votre code ici

### Coût moyen en fonction du prix

In [ ]:
#Ecrivez votre code ici

### Coût moyen en fonction de l'ancienneté du bien

In [ ]:
#Ecrivez votre code ici

### Coût moyen en fonction de l'âge de l'assuré

In [ ]:
#Ecrivez votre code ici

### Coût moyen en fonction du genre

In [ ]:
#Ecrivez votre code ici